package com.dawat.farmer.mamits.utils;

public class ApiConstant {
    public static final String LOGIN_END_POINT = AppConstant.PREF_KEY_BASE + "login";
    public static final String OTP_VERIFY_END_POINT = AppConstant.PREF_KEY_BASE + "verifyLoginOtp";
    public static final String GET_SLIDER_LIST_END_POINT = AppConstant.PREF_KEY_BASE + "getSliderList";
    public static final String GET_WEATHER_END_POINT = "https://api.weatherapi.com/v1/";
    public static final String GET_NEWS_LIST_END_POINT = AppConstant.PREF_KEY_BASE + "getNewsList";
    public static final String GET_NOTIFICATION_LIST_END_POINT = AppConstant.PREF_KEY_BASE + "getNotificationList";
    public static final String GET_SRP_STAGE_LIST_END_POINT = AppConstant.PREF_KEY_BASE + "getSrpReportStageList";
    public static final String GET_SRP_REPORT_LIST_END_POINT = AppConstant.PREF_KEY_BASE + "getSrpReportList";
    public static final String GET_SRP_QUESTION_LIST_END_POINT = AppConstant.PREF_KEY_BASE + "getQuestionList";
    public static final String GET_SRP_SUB_QUESTION_LIST_END_POINT = AppConstant.PREF_KEY_BASE + "getSubquestionList";
    public static final String GET_SRP_ANSWER_LIST_END_POINT = AppConstant.PREF_KEY_BASE + "getSrpReportDetail";
    public static final String GET_USER_DETAILS_END_POINT = AppConstant.PREF_KEY_BASE + "getFarmerProfile";
    public static final String GET_APPEAL_LIST_END_POINT = AppConstant.PREF_KEY_BASE + "getAppealList";
    public static final String GET_TICKET_LIST_END_POINT = AppConstant.PREF_KEY_BASE + "getTicketList";
    public static final String GET_CREATE_TICKET_END_POINT = AppConstant.PREF_KEY_BASE + "addTicket";
    public static final String GET_CREATE_APPEAL_END_POINT = AppConstant.PREF_KEY_BASE + "addAppeal";
    public static final String GET_SRP_CATEGORY_END_POINT = AppConstant.PREF_KEY_BASE + "getSrpCategoryList";
    public static final String GET_SRP_SUB_CATEGORY_END_POINT = AppConstant.PREF_KEY_BASE + "getSrpSubCategoryList";
    public static final String GET_PRODUCT_LIST_END_POINT = AppConstant.PREF_KEY_BASE + "getProductList";
    public static final String GET_PRODUCT_DETAIL_END_POINT = AppConstant.PREF_KEY_BASE + "getProductDetail";
    public static final String ADD_TO_CART_END_POINT = AppConstant.PREF_KEY_BASE + "addToCart";
    public static final String DELETE_FROM_CART_END_POINT = AppConstant.PREF_KEY_BASE + "deleteItem";
    public static final String GET_CART_LIST_END_POINT = AppConstant.PREF_KEY_BASE + "viewCart";
    public static final String CHECKOUT_ORDER_END_POINT = AppConstant.PREF_KEY_BASE + "placeOrder";
    public static final String CANCEL_ORDER_END_POINT = AppConstant.PREF_KEY_BASE + "updateOrderStatus";
    public static final String GET_ORDER_LIST_END_POINT = AppConstant.PREF_KEY_BASE + "orderList";
    public static final String GET_ORDER_DETAIL_END_POINT = AppConstant.PREF_KEY_BASE + "orderDetail";
    public static final String UPLOAD_SIGN_END_POINT = AppConstant.PREF_KEY_BASE + "uploadSignature";
    public static final String GET_SRP_BLOGS_END_POINT = AppConstant.PREF_KEY_BASE + "getSrpEventList";
    public static final String GET_BLOGS_END_POINT = AppConstant.PREF_KEY_BASE + "getEventList";
    public static final String GET_BLOG_DETAIL_END_POINT = AppConstant.PREF_KEY_BASE + "getEventDetail";
    public static final String GET_NEWS_DETAIL_END_POINT = AppConstant.PREF_KEY_BASE + "getNewsDetail";
    public static final String SEND_MESSAGES_LIST_END_POINT = AppConstant.PREF_KEY_BASE + "sendMessage";
    public static final String GET_MESSAGES_LIST_END_POINT = AppConstant.PREF_KEY_BASE + "getMessageList";
    public static final String GET_FARMER_BASIC_DETAILS_END_POINT = AppConstant.PREF_KEY_BASE + "getFarmerDetail";
    public static final String GET_CROPS_END_POINT = AppConstant.PREF_KEY_BASE + "getFarmCropList";
    public static final String GET_FARM_FIELD_END_POINT = AppConstant.PREF_KEY_BASE + "getFarmFieldListByFarm";
    public static final String GET_FARMS_END_POINT = AppConstant.PREF_KEY_BASE + "getFarmList";
    public static final String GET_LAND_DETAILS_END_POINT = AppConstant.PREF_KEY_BASE + "getFarmLandList";
    public static final String GET_IRRIGATION_SOURCES_END_POINT = AppConstant.PREF_KEY_BASE + "getFarmIrrigationSourceList";
    public static final String GET_FERTILIZATION_LIST_END_POINT = AppConstant.PREF_KEY_BASE + "getFarmFertilization";
    public static final String GET_HARVESTING_END_POINT = AppConstant.PREF_KEY_BASE + "getFarmHarvestingList";
    public static final String GET_IRRIGATION_LIST_END_POINT = AppConstant.PREF_KEY_BASE + "getFarmIrrigationList";
    public static final String GET_LABOR_END_POINT = AppConstant.PREF_KEY_BASE + "getFarmLaborList";
    public static final String GET_MACHINERY_END_POINT = AppConstant.PREF_KEY_BASE + "getFarmMachineryList";
    public static final String GET_NURSERY_END_POINT = AppConstant.PREF_KEY_BASE + "getFarmNurseryList";
    public static final String GET_PLANT_PROTECTION_END_POINT = AppConstant.PREF_KEY_BASE + "getFarmPlantProtectionList";
    public static final String GET_PURCHASING_END_POINT = AppConstant.PREF_KEY_BASE + "getFarmPurchasingList";
    public static final String GET_TRANSPLANTATION_END_POINT = AppConstant.PREF_KEY_BASE + "getFarmTransplantationList";
    public static final String GET_TREATMENT_END_POINT = AppConstant.PREF_KEY_BASE + "getFarmTreatmentList";
    public static final String GET_COC_END_POINT = AppConstant.PREF_KEY_BASE + "getFarmCultivationList";

}
